final: main.o graph.o linkedlist.o heap.o queue.o
	cc main.o graph.o linkedlist.o heap.o queue.o -o final
main.o: main.c
	cc -c main.c
graph.o: graph.h graph.c
	cc -c graph.c
heap.o: heap.h heap.c
	cc -c heap.c
queue.o: queue.h queue.c
	cc -c queue.c
linkedlist.o: linkedlist.h linkedlist.c
	cc -c linkedlist.c

